### PR TITLE
Add JupyterHub documentation

### PR DESCRIPTION
**Pull request by Cadair**
DO NOT MERGE.

This is the documentation for the currently offline JupyterHub.

@mikecroucher

### CODE REVIEW

**Comment by Cadair** [comment]
@mikecroucher suggestions of better places to put this structurally are very welcome.

**Comment by mikecroucher** [comment]
How about a 'methods of access' section in the documentation? We currently have 

1. Traditional ssh using various software - Exceed, MobaXterm, linux terminal etc.
2. The desktop thingy that I never liked much. (Will need someone to document that since I don't know anything about it)
3. Jupyter notebook

In the future, there could be more. For example, one day I'd like to have the ability to submit Ansys jobs (say) direct from Anays running on a desktop.

**Comment by Cadair** [comment]
@mikecroucher I have added a couple of stubs and the jupyter documentation to a new "Accessing Iceberg" section under "Using Iceberg".

What do you think?

**Comment by mikecroucher** [comment]
Yep. That's the kind of direction I was thinking.

**Comment by Cadair** [comment]
@mikecroucher happy to merge this with the subs as is? Seeing how the hub is now online?

**Comment by mikecroucher** [comment]
Yes. We can improve iteratively.
Nice work on getting the hub online.

**Pull request merged**
