### PR TITLE
Deniz's and Stuart's restructuring

### PR DESCRIPTION
**Pull request by Cadair**
This is a PR for the new `unify` branch in which @cs1ds and @cadair are working to tidy up the landing page and the general structure of the repo so that we can start porting more content over from the CMS.

Built preview of this branch is here: http://rcg.group.shef.ac.uk/unify/

### CODE REVIEW

**Comment by Cadair** [comment]
DO NOT MERGE

**Comment by Cadair** [comment]
@mikecroucher I have done a bit of re-theming on this branch. Your opinions would be welcomed.

**Comment by Cadair** [comment]
ping @cs1ds @mikecroucher this branch is now bring built by drone here: http://rcg.group.shef.ac.uk/unify/

**Comment by mikecroucher** [comment]
Looks good overall. There is some weird behaviour on the left hand side menu (on Chrome on Mac at least) at http://rcg.group.shef.ac.uk/unify/software/apps/index.html 

Try scrolling down.

**Comment by Cadair** [comment]
yeah I just noticed that, looks like it might be a padding issue.

**Comment by cs1ds** [comment]
I love the new navigation layout !!!!

 It will make moving from CMS to RCG almost seemless.

The saga of the snail-pace local HTML preview is continuing.  Hopefully my
upgraded Ubuntu box will circumvent this annoying windows problem.



On 14 October 2015 at 14:05, Stuart Mumford <notifications@github.com>
wrote:

> ping @cs1ds <https://github.com/cs1ds> @mikecroucher
> <https://github.com/mikecroucher> this branch is now bring built by drone
> here: http://rcg.group.shef.ac.uk/unify/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/pull/129#issuecomment-148043352>
> .
>



-- 
---------
Knowledge leads to understanding. Understanding leads to wisdom.
------
Dr Deniz Savas
Tel: +44 (0)11422 23 0 23
Fax: +44(0)11422 21 1 88
URL: www.shef.ac.uk/wrgrid
        dsavas.staff.shef.ac.uk

**Comment by Cadair** [comment]
The scrolling issue has been hacked around, and I have updated the style for the left menu to add some distinction between levels, using the same colour scheme as the university website.

Take a look.

**Pull request merged**
