### PR TITLE
matlab compiler

### PR DESCRIPTION
**Pull request by cs1ds**
Added Matlab Compiler related info

### CODE REVIEW

**Comment by Cadair** [comment]
issue 300 Deniz ;)

**Comment by Cadair** [comment]
issue number 300. Also don't edit my comments :p

**Comment by cs1ds** [comment]
Perhaps here ! I think I found it !

**Comment by cs1ds** [comment]
Why is it taking so long to complete the checks ? ( Stuck on 1 pending check )

**Comment by cs1ds** [comment]
And who is Travis anyway ????

**Comment by cs1ds** [comment]
I think it is just finished !!!!

**Pull request merged**
