### PR TITLE
rename compilers to development tools

### LINKED ISSUE #109: Change 'Compilers' to 'Development Tools'
The Compilers section currently has CMake and git along with the compilers. I suggest that we rename this section 'Development Tools'.

### PR DESCRIPTION
**Pull request by Cadair**
this closes #109

### CODE REVIEW

**Comment by Cadair** [comment]
@cs1ds What do you think of this?

**Comment by cs1ds** [comment]
We could use both descriptions (i.e.  Compilers & Development Tools )

**Comment by Cadair** [comment]
That might get a little long as a title for the sidebar, but we could call it that from the main body of the software page?

**Comment by mikecroucher** [comment]
Compilers *are* development tools :)

**Comment by Cadair** [comment]
well yes, but that might not jump straight to the front of peoples minds when looking for them. I don't thin we should (also we can't for practical reasons) have both in the title.

**Comment by cs1ds** [comment]
See latest unify branch

**Comment by Cadair** [comment]
Yeah cool. We can use that.

**Comment by cs1ds** [comment]
Stuart, If there are no objections to the recent changes to the unify branch, can you update the live pages by pulling the unify changes please ?

**Comment by Cadair** [comment]
@cs1ds I put some comments on the PR to pull unify into master.

**Pull request closed without merging**
